# file      : buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

# Note that the project directories order is important (prerequisites goes
# first).
#
d = libbutl/ build2/ libsqlite3/ libodb/ libodb-sqlite/ libbpkg/ bpkg/ doc/

i =               \
INSTALL           \
UPGRADE           \
BOOTSTRAP-MACOSX  \
BOOTSTRAP-MINGW   \
BOOTSTRAP-MSVC    \
BOOTSTRAP-UNIX    \
BOOTSTRAP-WINDOWS

./: $d doc{$i README version} cli{$i} file{build.sh build-*} file{manifest}

doc{version}: file{manifest} # Generated by the version module.
doc{version}: dist = true

# Don't install the BOOTSTRAP/INSTALL files. But UPGRADE could be useful.
#
doc{INSTALL}@./:  install = false
doc{BOOTSTRAP-*}: install = false
